version: '3.4'

networks:

  monorepo-network:
    name: visual-studio-monorepo
    external: false



volumes:
  static-content:
  rabbitmq:
    driver: local


services:

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: monorepo-rabitmq
    networks:
      - monorepo-network
    ports:
      - "7100:15672"
      - "7101:5672"
    volumes:
      - rabbitmq:/rabbitmq

  sampleservice01:
    image: ${DOCKER_REGISTRY-}monorepo-sampleservice01
    container_name: monorepo-sampleservice01
    build:
      context: ./SampleService01
      dockerfile: SampleService01.dockerfile
    networks:
      - monorepo-network
    volumes:
      - static-content:/usr/src/app/public




