version: '3.4'

networks:

  monorepo-network:
    name: visual-studio-monorepo


volumes:

  rabbitmq:
    driver: local


services:

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: monorepo-rabitmq
    networks:
      - monorepo-network
    ports:
      - "7100:15672"
      - "7101:5672"
    volumes:
      - rabbitmq:/rabbitmq
    # logging:
    #   driver: "none"

  sampleservice01:
    image: ${DOCKER_REGISTRY-}monorepo-sampleservice01
    container_name: monorepo-sampleservice01
    depends_on:
      - rabbitmq
    build:
      context: .
      dockerfile: SampleService01.dockerfile
    networks:
      - monorepo-network
    # logging:
    #   driver: "none"



