version: '3.4'

networks:

  monorepo-network:
    name: visual-studio-monorepo
    external: false



volumes:
  static-content:

  rabbitmq:
    driver: local

  eventstore-data:
  eventstore-logs:

  kafka_data:


services:


  # sql-server:
  #   image: mcr.microsoft.com/mssql/server:latest
  #   container_name: monorepo-sql-server
  #   networks:
  #     - monorepo-network
  #   environment:
  #     ACCEPT_EULA: 'Y'
  #     SA_PASSWORD: ''
  #   ports:
  #     - 1433:1433
  #   # logging:
  #   #   driver: "none"


  # kafka:
  #   image: docker.io/bitnami/kafka:3.5
  #   container_name: monorepo-kafka
  #   networks:
  #     - monorepo-network
  #   ports:
  #     - "9092:9092"
  #   volumes:
  #     - "kafka_data:/bitnami"
  #   environment:
  #     # KRaft settings
  #     - KAFKA_CFG_NODE_ID=0
  #     - KAFKA_CFG_PROCESS_ROLES=controller,broker
  #     - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
  #     # Listeners
  #     - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
  #     - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
  #     - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
  #     - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
  #     - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
  #   # logging:
  #   #   driver: "none"

  # eventstoredb:
  #   image: eventstore/eventstore:latest
  #   container_name: monorepo-eventstore
  #   networks:
  #     - monorepo-network
  #   environment:
  #     - EVENTSTORE_INSECURE=true # let eventstore run without ceritficate
  #     - EVENTSTORE_EXT_TCP_PORT=1113 # set internal tcp port
  #     - EVENTSTORE_HTTP_PORT=2113 # set internal admin ui port
  #     - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
  #   ports:
  #     - "1113:1113" # map internal tcp port
  #     - "2113:2113" # map internal admin ui port
  #   volumes:
  #     - type: volume
  #       source: eventstore-data
  #       target: /var/lib/eventstore
  #     - type: volume
  #       source: eventstore-logs
  #       target: /var/log/eventstore
  #   # logging:
  #   #   driver: "none"

  # rabbitmq:
  #   image: "rabbitmq:3-management"
  #   container_name: monorepo-rabitmq
  #   networks:
  #     - monorepo-network
  #   ports:
  #     - "7100:15672"
  #     - "7101:5672"
  #   volumes:
  #     - rabbitmq:/rabbitmq
  #   # logging:
  #   #   driver: "none"

  sampleservice01:
    image: ${DOCKER_REGISTRY-}monorepo-sampleservice01
    container_name: monorepo-sampleservice01
    build:
      context: .
      dockerfile: SampleService01.dockerfile
    networks:
      - monorepo-network
    volumes:
      - static-content:/usr/src/app/public
    # logging:
    #   driver: "none"



