version: '3.4'

networks:

  sample-network:
    name: visual-studio-sample
    external: false

services:

  sampleservice01:
    image: ${DOCKER_REGISTRY-}sampleservice01
    container_name: sampleservice01
    build:
      context: .
      dockerfile: SampleService01/Dockerfile
    networks:
       - sample-network
   # logging:
   #   driver: "none"