version: '3.4'

services:
  sampleservice01:
    image: ${DOCKER_REGISTRY-}sampleservice01
    container_name: sampleservice01
    build:
      context: .
      dockerfile: SampleService01/Dockerfile
