version: '3.4'

networks:

  sample-network:
    name: visual-studio-sample
    external: false

services:

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabitmq
    networks:
      - sample-network
    ports:
      - "7100:15672"
      - "7101:5672"
    volumes:
      - rabbitmq:/rabbitmq
    # logging:
    #   driver: "none"


  sampleservice01:
    image: ${DOCKER_REGISTRY-}sampleservice01
    container_name: sampleservice01
    depends_on:
      - rabbitmq
    build:
      context: .
      dockerfile: SampleService01/Dockerfile
    networks:
       - sample-network
   # logging:
   #   driver: "none"

