version: '3.4'

volumes:

  rabbitmq:
    driver: local

networks:

  default:
    driver: bridge

services:

  sampleservice01-rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: sampleservice01-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
         # AMQP protocol port
        - 5672:5672
        # HTTP management UI
        - 15672:15672
    volumes:
      - rabbitmq:/rabbitmq
    # logging:
    #   driver: "none"


  sampleservice01:
    image: ${DOCKER_REGISTRY-}sampleservice01
    container_name: sampleservice01
    depends_on:
      - sampleservice01-rabbitmq
    build:
      context: .
      dockerfile: SampleService01/Dockerfile
    environment:
     - RabbitMqHostname=sampleservice01-rabbitmq
     - RabbitMqUserName=guest
     - RabbitMqPassword=guest
     - RabbitMqPort=5672
     - RabbitMqContentType=application/json
     - RabbitMqExchange=amq.topic
   # logging:
   #   driver: "none"

