version: '3.4'


volumes:

  rabbitmq:
    driver: local

services:

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabitmq
    ports:
      - "7100:15672"
      - "7101:5672"
    volumes:
      - rabbitmq:/rabbitmq
    # logging:
    #   driver: "none"


  sampleservice01:
    image: ${DOCKER_REGISTRY-}sampleservice01
    container_name: sampleservice01
    depends_on:
      - rabbitmq
    build:
      context: .
      dockerfile: SampleService01/Dockerfile
    environment:
     - RabbitMqHostname=localhost
     - RabbitMqUserName=guest
     - RabbitMqPassword=guest
     - RabbitMqPort=7101
     - RabbitMqContentType=application/json
     - RabbitMqExchange=buyerexchange
   # logging:
   #   driver: "none"

